### ISSUE TITLE
unable to take debug ios build

### ISSUE THREAD

**Issue by jeeva1803** [gameclosure/devkit-core#26]
The project is running well in browser, but when i try take build for ios (devkit debug native-ios), im getting the following error.
[build]    [error]  build failed         
[build]    [error]  Error: No ios config found for     at getModuleConfig (/home/lakeba/projects/wordfinder/modules/devkit-core/modules/native-ios/build.js:26:11)     at installModule (/home/lakeba/projects/wordfinder/modules/devkit-core/modules/native-ios/build.js:43:24)     at /home/lakeba/projects/wordfinder/modules/devkit-core/modules/native-ios/build.js:209:7

**Comment by jwilm** [comment]
Can you post the output of `tree -L 2 modules`? If you're on mac, you can install tree from homebrew `brew install tree`. If on linux, I would expect it's either preinstall or available via apt.

**Comment by jeeva1803** [comment]
the output of tree -L 2 modules run from run from /home/lakeba/projects/wordfinder is as follows,

modules
|-- adAggregator
|   |-- android
|   |-- js
|   |-- package.json
|   |-- package.json~
|   `-- README.md
|-- appflood
|   |-- android
|   |-- ios
|   |-- js
|   |-- package.json
|   |-- package.json~
|   `-- README.md
|-- devkit-billing
|   |-- android
|   |-- ios
|   |-- js
|   |-- package.json
|   `-- README.md
|-- devkit-core
|   |-- modules
|   |-- node_modules
|   |-- package.json
|   |-- scripts
|   `-- src
|-- devkit-facebook
|   |-- android
|   |-- build
|   |-- ios
|   |-- js
|   |-- node_modules
|   |-- package.json
|   |-- README.md
|   |-- test
|   `-- test-app
|-- devkit-localnotify
|   |-- android
|   |-- ios
|   |-- js
|   |-- package.json
|   `-- README.md
|-- googleLogin
|   |-- android
|   |-- js
|   |-- package.json
|   |-- package.json~
|   `-- README.md
`-- ortc
    |-- android
    |-- index.js
    |-- js
    |-- package.json
    `-- package.json~

34 directories, 19 files

**Comment by mgh** [comment]
Hey @jeeva1803, did you get this fixed?  If not, can you run `devkit modules` in your game directory and send us the output?

One of your modules is looking for a file, probably `./ios/config.json`, but it doesn't exist.  If it's a custom module you've written yourself, you should check `package.json` for the key `devkit.extensions.ios`. If it's present and specifies a folder that doesn't exist or doesn't contain a `config.json`, the build will fail.  You can remove the key from that module's `package.json`.  Of course, this is assuming the module isn't providing any iOS custom code. If it is, you'll need to provide a `config.json` file.

If the module that is failing is not your code, you can still update `package.json` as a temporary fix, but you should contact the module owner so they can fix it as well.  If it's one of our modules, the output of `devkit modules` will likely show us that one of your modules is on an old version and we can tell you which version to switch to.
